# Generated by Django 5.1.4 on 2025-01-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_cart_total_price_alter_orderitem_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='discount_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
