# Generated by Django 5.1.3 on 2024-12-08 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_address_detailed_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must start with '09' and be 11 digits long.", regex='^09\\d{9}$')]),
        ),
    ]
