# Generated by Django 5.1.4 on 2025-01-19 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_options_alter_customer_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='otp_expiry',
        ),
    ]
