# Generated by Django 5.1.3 on 2024-12-17 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productfeature_product_brand_product_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeature',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='product.product'),
            preserve_default=False,
        ),
    ]
