# Generated by Django 5.1.3 on 2024-12-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discounts',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.discount'),
        ),
    ]
