# Generated by Django 5.1.4 on 2025-01-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_discounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='max_amount',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
