# Generated by Django 5.1.4 on 2025-01-17 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_discount_max_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'تخفیف', 'verbose_name_plural': 'تخفیف\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productfeature',
            options={'verbose_name': 'ویژگی محصول', 'verbose_name_plural': 'ویژگی\u200cهای محصول'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='product.category', verbose_name='دسته\u200cبندی والد'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='amount',
            field=models.IntegerField(verbose_name='مقدار تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='end_date',
            field=models.DateTimeField(verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='max_amount',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='حداکثر تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='start_date',
            field=models.DateTimeField(verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.CharField(choices=[('PG', 'درصدی'), ('FA', 'مقدار ثابت')], max_length=20, verbose_name='نوع تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.TextField(max_length=50, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=250, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discounts',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.discount', verbose_name='تخفیف\u200cها'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, max_length=500, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.TextField(max_length=50, verbose_name='مدل'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='display_order',
            field=models.IntegerField(verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='key',
            field=models.CharField(max_length=50, verbose_name='ویژگی'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='product.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='value',
            field=models.CharField(max_length=50, verbose_name='مقدار'),
        ),
    ]
